apiVersion: v1
kind: Service
metadata:
  name: guestbook-1
spec:
  ports:
    - port: 80
  selector:
    app: guestbook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook-1
  template:
    metadata:
      labels:
        app: guestbook-1
    spec:
      containers:
        - name: guestbook-1
          image: gcr.io/google-samples/gb-frontend:v4
          ports:
            - containerPort: 80
